version: "3"

services:
  # api gateway
  screenshot:
    image: stcsolutions/screenshot
    volumes:
      - ./screenshots:/usr/src/screenshots
      - ~/.config/gcloud/:/root/.config/gcloud/:ro
    ports:
      - 5000:5000
    environment:
      - SCREENSHOT_PATH=${SCREENSHOT_PATH}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
