version: "3"

services:
  # api gateway
  screenshot:
    image: stcsolutions/screenshot
    volumes:
      - ./.google-cloud.json/:/usr/src/.google-cloud.json:ro
    ports:
      - 5000:5000
    environment:
      - SCREENSHOT_PATH=${SCREENSHOT_PATH}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
