type Query {
  "Take screenshot"
  takeScreenshot(url: String!, width: Int, height: Int, name: String, wait: Int,
    includeDate: Boolean): [Screenshot!]
}

type Screenshot {
  "URL of image in bucket"
  url: String!

  "Image in base64"
  base64: String!

  "Image created at"
  createdAt: String!
}
